### ISSUE TITLE
Problem compiling read-bmp180-si7021-right.lua with ESPlorer V0.2.0-rc2

### ISSUE THREAD

**Issue by Jasea** [NodeUSB/NodeUSB#4]
When using ESPlorer to compile read-bmp180-si7021-right.lua by pressing "Save to ESP" Nesting errors are detected at lines 18,19 and 38,39 relating to the bracketing around the %s in the middle of each line. This is surprising as the program complies without error when using NodeUSB - IDE. 
A similar problem exist with program init-bmpo85-si7021.lua

**Comment by mikewen** [comment]
This is a bug in certain versions of ESPlorer. You can change the [[%s]] to "%S"

**Comment by Jasea** [comment]
Mike, Thank you. With my version the problem was fixed with "%s"
