### ISSUE TITLE
5V on J3?

### ISSUE THREAD

**Issue by boneskull** [NodeUSB/NodeUSB#5]
I've set up my BMP180 module, plugged it into J3, but it isn't being recognized.  wondering if it was broken, I stuck my multimeter into the board, and it's receiving 5V.  the wiki mentions to power this device with 3.3V.  What's the deal..?

**Comment by mikewen** [comment]
J3 are 3 GPIO pins and GND, they are all 3.3V. ( J2 is 5V )
https://github.com/NodeUSB/NodeUSB/wiki/NodeUSB-pinouts

You can just send one GPIO pin to high and supply power to BMP180.

**Comment by boneskull** [comment]
thanks
