### ISSUE TITLE
Power problem

### ISSUE THREAD

**Issue by mdcom77** [NodeUSB/NodeUSB#6]
The problem is when I plug NodeUSB into USB power bank, or usb charger it wont work. Blue diode is flashing but module do not connection to AP.
When I do the same with debugger/flasher it works OK. 
Debugger/flasher is plugged in USB power bank and then NodeUSB is plugged into flasher.
When plugged directly into USB power bank do not work. 
Guess this cold be 3.3/5v problem but not sure.
Can someone help with this?

**Comment by mikewen** [comment]
It is likely the problem with USB power bank and the USB charger. 
Do you have another good quality USB charge you can try?

I tested iPhone, iPAD charger, both work.

**Comment by mikewen** [comment]
The problem is finally solved. 
Please see wiki:
https://github.com/NodeUSB/NodeUSB/wiki/Compatibility-problem-with-some-USB-power-chargers
